version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: fraud_user
      POSTGRES_PASSWORD: fraud_pass
      POSTGRES_DB: frauddb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://fraud_user:fraud_pass@db:5432/frauddb
    depends_on:
      - db

volumes:
  pgdata:
